### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Booteille** [jlm2017/melenphone#2]
Bonjour,

J'aurais aimé savoir quel est l'intérêt d'un outil comme Google Analytics pour un site comme FiPhone ?
Si l'intérêt se révèle réel, n'y a-t-il pas la possibilité de remplacer Google Analytics par un outil comme [Matomo](https://matomo.org/) et d'expliquer clairement quelles sont les données collectées et pourquoi, conformément aux[ nouvelles lois européennes](https://fr.wikipedia.org/wiki/R%C3%A8glement_g%C3%A9n%C3%A9ral_sur_la_protection_des_donn%C3%A9es) qui entreront bientôt en vigueur ?

J'apprécierais grandement que les différents services proposés par la France Insoumise ne soient pas bourrés de trackers inutiles et nuisant à l'image du mouvement !

**Comment by jillro** [comment]
Quelques explications sur le remplacement de GA par Matomoto que nous souhaitons à terme : https://twitter.com/Guilrobis/status/960957211727073280. Nous allons bientôt mener des expérimentations, en attendant, nous ne pouvons pas maintenir deux outils.

**Comment by Booteille** [comment]
D'accord, merci pour la réponse.

J'ai tout de même toujours du mal à comprendre en quoi un outil de tracking est utile pour un service comme le FiPhone. Pourrais-je avoir quelques explications m'indiquant en quoi c'est indispensable ?
